name: "PR Checks"
on: push

permissions:
    contents: read

jobs:
    unit:
        runs-on: ubuntu-latest
        name: Unit Tests
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                node-version: 20
                cache: 'npm'
            - run: npm install
            - run: npm test

    e2e:
        runs-on: ubuntu-latest
        name: E2E Test
        needs: unit
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                node-version: 20
                cache: 'npm'
            - uses: ./
              with:
                key: ${{ secrets.TB_KEY }}
                secret: ${{ secrets.TB_SECRET }}
                tunnelIdentifier: github-action-tunnel
            - run: npm install
            - run: npm run test:e2e
              env:
                TB_KEY: ${{ secrets.TB_KEY }}
                TB_SECRET: ${{ secrets.TB_SECRET }}